on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: |
          cd target/release
          chmod +x rustymind
          gzip -c rustymind > rustymind-x86_64-linux.gz
      - uses: actions/create-release@v1
        id: create_release  # needed for upload_url later
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/rustymind-x86_64-linux.gz
          asset_name: rustymind-x86_64-linux.gz
          asset_content_type: application/x-gzip
